# The scope of code that Rubocop should lint. Use this if you only want to lint changed files. If this is not set
# or not equal to 'modified', Rubocop is run against the entire codebase. Note that this will not work on the master branch.
# Valid options: 'modified'
# Default: nil
# check_scope: 'modified'
rubocop_fail_level: 'refactor'

# Description: Versions required to run your RuboCop checks. These should match those in Gemfile.lock
versions:
