name: Rubocop

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Identifying versions.
      run: |
          grep '^    rubocop.* (' Gemfile.lock |
            sed 's/^   /  -/' |
            sed "s/)/'/g" |
            sed "s/ (/: '/g" >> .github/config/rubocop_linter_action.yml
    - name: Rubocop
      uses: andrewmcodes/rubocop-linter-action@v3.2.0
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
